name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - matplotlib
  - numpy
  - jupyterlab-fasta
  - jupyterlab-geojson
  - jupyterlab-katex
  - jupyterlab-mathjax2
  - jupyterlab-vega3
  - sympy
  - jupyter
  - ipywidgets
  - texlive-core
  - pip
  - pip:
    - nbgitpuller
