name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - matplotlib
  - numpy
  - mathjax
  - sympy
  - jupyter
  - ipywidgets
  - texlive-core
  - pip
  - pip:
    - nbgitpuller
